### ISSUE TITLE
Can I donate you money?

### ISSUE THREAD

**Issue by rnmp** [isaacwisdom/RemarkableLamyEraser#19]
Hey @isaacwisdom!

Thanks for such a simple way to add this functionality. This is the sort of thing I would've paid for so I wonder if you have a donation link or perhaps a charity you'd like me to donate $10 to.

**Comment by isaacwisdom** [comment]
Hey, I'm glad to hear that you enjoy the tool! I wouldn't feel right taking money for the project since I haven't made any progress on it in about a year. But if you'd like to send money somewhere, my charity of choice would be the [American Alzheimer's Association.](https://www.alz.org)

Happy erasing!

**Comment by rnmp** [comment]
@isaacwisdom Done!
