### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Jonnie-Cache** [isaacwisdom/RemarkableLamyEraser#35]
Is there a way to get the button to use the Lasso Erase tool instead of the standard erase?

**Comment by DrAhoss** [comment]
Would love to see this too! I am yet to test this plugin, but I really prefer the lasso tool over the 'classic' eraser, since I frequently select and move stuff and I have experienced, that sometimes the eraser lines are moved over other written text aswell. It doesn't make sense in the first place, but that's why I prefer the lasso tool.

**Comment by brandonkboswell** [comment]
Another bump for the Lasso eraser.

**Comment by isaacwisdom** [comment]
Hi all!
If you use the v2 branch, this feature has been implemented. However, it isn't very reliable, so I've been hesitant to fully release v2. (For what it's worth, the select tool is much more reliable.) However, I'd encourage you all to give it a try and see if it fits your needs.

The v2 branch is much more customizable, so you'll have to configure it to use the lasso eraser. The readme should have all the information you need!

**Comment by ishanina** [comment]
Hey! I'm having trouble getting the select erasor tool to work on v2. When I don't change the config file at all, it works, but when change press and hold to say eraser-selection instead of eraser, it stops working. If you have any thoughts it would be much appreciated!

**Comment by isaacwisdom** [comment]
Closed as this is implemented in the v2 branch.
