### ISSUE TITLE
Switch to Highlighter

### ISSUE THREAD

**Issue by brandonkboswell** [isaacwisdom/RemarkableLamyEraser#40]
Hey Isaac,

I know it's a bit out of scope for the project, but it seems like you just about have support for this. The new Kindle Scribe pen has both an eraser and an eraser button, it would be amazing if the eraser button could switch to the highlighter while held (or toggle on press). Do you think this would be possible?

**Comment by isaacwisdom** [comment]
It could be possible, but it would be hard for me to implement without having access to my own pen to test with. That being said, to check if this is even possible, I'll need some information first.
Could you:
1. Install [toltec](https://toltec-dev.org) (pay attention to the warnings about compatible os versions) and then install the "evtest" package.
2. Run the command`evtest /dev/input/event1 | grep -v "ABS\|SYN"` (if using an RM1, change 'event1' to 'event0')
3. Near the screen, click the pen once and use the eraser once, then paste the output here.

Thanks!

**Comment by brandonkboswell** [comment]
@isaacwisdom an alternative way this could potentially be done is by doing switch to last tool macro similar to the swipe down from the top-right in @ddvk's hack. I'm not sure his implementation though.

**Comment by isaacwisdom** [comment]
Unfortunately, the way that @ddvk's hack and mine own are very different in implementation. ddvk's hack is a pretty involved modification which works by installing a modified xochitl process that can be interacted with in software (an amazing feat on it's own, as it required reverse engineering the machine code since reMarkable doesn't supply the xochitl source code), whereas mine is much more topical, simulating button presses and pen actions as if the user had done them themself.

This is pretty intentional, however. I wanted something much less invasive than DDVK's tool, which led me to creating this project. However, it means that the code is "dumb" (it has no knowledge of the state of the machine since it can't read internal states of xochitl), and has no way of knowing what the last tool used is.

**Comment by isaacwisdom** [comment]
> Unfortunately, I am on reMarkable 3.0.4.1292, so I don't have access to toltec. From everything I've tested, the button responds the same as the eraser button on my Lamy and S-Pen as I was able to use the eraser button while using the V1 RemarkableLamyEraser.

Do you mean that you were able to trigger events (such as double pressing to undo) with the button on the Kindle Scribe pen?

**Comment by brandonkboswell** [comment]
I have tried it with left-handed standard erase. I can test the
double-press later today.

**Comment by brandonkboswell** [comment]
Perhaps I'm doing something wrong, but I can get toggle to work with all of my pens, but I'm not having any luck with double press on any of them. Lamy Al-Star, Samsung S-Pan & Kindle Scribe Pen.

Here's my config line:  /usr/sbin/RemarkableLamyEraser --left-handed --toggle --double-press redo

**Comment by isaacwisdom** [comment]
You've got the double click mapped to redo, and not undo, meaning you have to manually undo something before the redo will work. Is this your intention?

**Comment by brandonkboswell** [comment]
I just retried it with /usr/sbin/RemarkableLamyEraser --left-handed --toggle --double-press undo, and I find that I can't get undo on double-press to fire with any of the three stylus. The toggle works, but double pressing doesn't seem to undo.

**Comment by isaacwisdom** [comment]
Cool, I think I might know what the problem is.


Can you try installing from the V2 branch and using the double press from there? The V2 branch is smarter about checking the tablets orientation.

Additionally, on the V1 branch, can you try the double press without the left-handed flag? (make sure to change your remarkable to be right handed too)

**Comment by brandonkboswell** [comment]
@isaacwisdom that was it. I use my tablet in landscape so that was likely the issue. V2 works as expected for all of the stylus, including the Kindle Scribe stylus.

**Comment by se1961** [comment]
Off topic a bit: I am using this modification with 3.1, and it works beautifully. I am hoping to install the beta version, but can't figure out how to install the V2 branch. Is there a way to install the beta from a command line, or is one obliged to follow the "build" instructions, which are outside of my tech comfort zone? 🙂

**Comment by slotThe** [comment]
Should work in https://github.com/slotThe/RemarkableLamyEraser/ and thus also on the `main` branch (and at some point this repo will use that as its default branch!)
