### ISSUE TITLE
Seems that we are looking at the previous version rather than the current version on the version check

### ISSUE THREAD

**Issue by javalasers** [isaacwisdom/RemarkableLamyEraser#61]
https://github.com/isaacwisdom/RemarkableLamyEraser/blob/8b8f163fd09586e789cdf72c161d2144247ebfa5/sources/orientation.c#LL138C16-L138C23

My reMarkable 2 UI shows version 3.4.01784. The check in the code above parses out the "PreviousVersion" string from xochitl.conf, which in my case is "3.3.2.1666"

I'm not sure where the current software version is stored programatically within the reMarkable, but this doesn't seem to be quite right...

**Comment by isaacwisdom** [comment]
Right, I remember this now. So it turns out there isn't an easy way to check the currently installed software version (well, there is, but it would involve implementing a sort of lookup table that I don't really want or need to do.) Ultimately, all the code needs to do is make sure the device is running at least 3.x.x.x, and checking the prior software version is sufficient for that purpose.

All that being said, I'll probably remove the printout about the device software version, and keep the check internal.

**Comment by isaacwisdom** [comment]
Fixed with https://github.com/isaacwisdom/RemarkableLamyEraser/commit/10ffa17e3c473459666a6157089879801a904000
